services:
  db:
    container_name: usermanage-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:15.3
    hostname: db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /var/lib/docker/volumes/usermanage_db:/var/lib/postgresql/data

  adminer:
    container_name: usermanage-adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usermanage-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always